import './globals.css';

import { ClientLayout } from './ClientLayout';
import { ApolloWrapper } from './ApolloWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ApolloWrapper delay={1000}>
          <ClientLayout>{children}</ClientLayout>
        </ApolloWrapper>
      </body>
    </html>
  );
}
